name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: 25
      - name: Cache generated data
        uses: actions/cache@v5.0.4
        with:
          path: |
            plugin/build/minecraft/
            plugin/build/generated/minecraft/mapping/
          key: minecraft-${{ hashFiles('gradle.properties') }}
      - name: Build LimboAPI
        run: ./gradlew build
      - name: Inspect SpotBugs Report
        if: always()
        run: |
          find . -path "*/reports/spotbugs/*" -type f -exec ls -la {} + || true
      - name: Upload LimboAPI Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LimboAPI
          path: "*/build/libs/*.jar"
      - name: Find git version
        if: ${{ github.event_name == 'push' }}
        id: git-version
        run: echo "id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Find correct JAR
        if: ${{ github.event_name == 'push' }}
        id: find-jar
        run: |
          output="$(find plugin/build/libs/ ! -name "*-javadoc.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "jarname=$output" >> $GITHUB_OUTPUT
      - name: Publish to GitHub Release
        if: ${{ github.event_name == 'push' }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: plugin/build/libs/${{ steps.find-jar.outputs.jarname }}
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: Dev-build ${{ steps.git-version.outputs.id }}
          tag: dev-build
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
